### ISSUE TITLE
can't create an account/ sign in. Password entry bug

### ISSUE THREAD

**Issue by vrnico** [usevolition/volition#118]
![passwordissue](https://i.imgur.com/ggJHVYx.png)

I've tried making/ signing in with a Google account on a self-hosted herokuapp, and on the usevolition.com portal. While I can't get the self-hosted sign up or sign on to work, I have been able to access my account through signing in through my Google account on the usevolition portal. Upon trying to sign up for an account on volition.com and in my heroku app I am unable to complete the form post because it is failing to reference it against the 100 most common passwords (pictured above). Any ideas on how to fix this?

Also any guidelines on running volition without authentication on a local vm?

**Comment by harshamurthy** [comment]
@vrnico, I'm looking into it. I'll try to recreate the issue on my end and figure out the solution. Will get back to you asap!

**Comment by harshamurthy** [comment]
@vrnico, thanks for your patience! I looked into what you said above:
1. Google account sign-in is disabled on self-hosted versions of Volition. Creating an account and signing in to the version of Volition we host at https://www.usevolition.com will create an account completely separate from your self-hosted account. You should not even see the option to sign in with Google on your self-hosted version.
2. The top 100 passwords check we were using was taken down which is what was causing the error when you were trying to create an account on your self-hosted version. I have submitted a pull request fixing this issue. It should be reviewed and merged into the master branch by tomorrow morning. Thanks for bringing that error to our attention!
3. Running Volition without authentication is a bit more complicated than it would seem. All of the information from to-dos and weekly plans are associated with a specific user, which requires authentication even if yours is the only account in the database because you are self-hosting.

I'll let you know as soon as the password error resolution is merged into the master branch. You can then redeploy to Heroku and sign up on your self-hosted version successfully!

**Comment by harshamurthy** [comment]
@vrnico, the fix has been pushed to master. Feel free to redeploy, you should be able to create an account on your self-hosted version without any issues now.

**Comment by vrnico** [comment]
@harshamurthy hey just redeployed, and was able to sign in! solid job!

**Comment by marcopatr** [comment]
Could it be that the error exists again? On a self-hosted herokuapp I see the same as the screenshot shows above. A login is not possible.
